language: python
python:
  - "3.5"
before_install:
  - mv .homeassistant/secrets.sample.yaml .homeassistant/secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c .homeassistant/ --script check_config