- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: triggered
  action:
  - service: notify.telegram_tostom
    data:
      message: 'I sensori hanno rilevato un movimento: {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}'
  - data: {}
    data_template:
      message: Allarme
    service: script.foto_telegram_continuative
  - service: media_player.volume_set
    data:
      entity_id: media_player.gh_living
      volume_level: 0.4
  - delay: '3'
  - entity_id: media_player.group_casa
    data_template:
      language: it
      message: I sensori hanno rilevato un movimento su {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name}}
    service: tts.google_say
- id: '1533930732910'
  alias: Telegram start
  trigger:
  - event_data:
      command: /luci
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      data:
        keyboard:
        - /accendiAndrea, /spegniAndrea
      message: commands
    service: notify.telegram_tostom
- id: '1533931219774'
  alias: Telegram accendi andrea
  trigger:
  - event_data:
      command: /accendiAndrea
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.andrea
- id: '1533935649774'
  alias: Telegram spegni andrea
  trigger:
  - event_data:
      command: /spegniAndrea
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.andrea
- id: '1507996878399'
  alias: Send_message_on_statechange
  trigger: []
  condition: []
  action: []
- id: '1535144179463'
  alias: Barilla
  trigger:
  - event_data: {}
    event_type: dash_button_barilla
    platform: event
  condition: []
  action:
  - service: script.1540935195507
- id: '1535147006654'
  alias: Duracell
  trigger:
  - event_data: {}
    event_type: dash_button_duracell
    platform: event
  condition: []
  action:
  - service: script.close_covers
- alias: Camera Center
  trigger:
    platform: state
    entity_id: input_select.camera_control
    to: Centro
  action:
    service: shell_command.camera_center
  id: 6ac0b990d63540b9b049925ef1e41845
- alias: Camera Sx
  trigger:
    platform: state
    entity_id: input_select.camera_control
    to: Sinistra
  action:
    service: shell_command.camera_sx
  id: 1a22e550327d4d3f8c543c56846509eb
- alias: Camera Dx
  trigger:
    platform: state
    entity_id: input_select.camera_control
    to: Destra
  action:
    service: shell_command.camera_dx
  id: ce41889e1cd64e23952509a60c8ed056
- alias: Camera Hide
  trigger:
    platform: state
    entity_id: input_select.camera_control
    to: Nascondi
  action:
    service: shell_command.camera_hide
  id: 599228f656c54ed09af6943b03f497c8
- id: '1540937413698'
  alias: Illy
  trigger:
  - event_data: {}
    event_type: dash_button_illy
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.allarme_disattivato
    service: switch.toggle
- id: '1545736810275'
  alias: Bentornato
  trigger:
  - entity_id: binary_sensor.portoncino
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.alarm_grace_time
    state: idle
  - condition: state
    entity_id: timer.alarm_back_home_time
    state: active
  action:
  - data:
      entity_id: light.soggiorno
    service: light.turn_on
  - data:
      entity_id: media_player.gh_living
      volume_level: 0.3
    service: media_player.volume_set
  - delay: '2'
  - data:
      entity_id: media_player.gh_living
      language: it
      message: Bentornato!
    service: tts.google_say
- id: '1545736810567'
  alias: Bentornato Tapparelle
  trigger:
  - entity_id: binary_sensor.portoncino
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    before: sunset
    before_offset: -00:10:00
    condition: sun
  - condition: state
    entity_id: timer.alarm_grace_time
    state: idle
  - condition: state
    entity_id: timer.alarm_back_home_time
    state: active
  action:
  - data:
      entity_id: cover.ground_floor
    service: cover.open_cover
  - data:
      entity_id: cover.first_floor
    service: cover.open_cover
  - delay: '25'
  - data:
      entity_id: light.soggiorno
    service: light.turn_off
- id: '1523957634674'
  alias: Accendi luce giardino all'apertura del portoncino
  trigger:
  - entity_id: binary_sensor.portoncino
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id:
      - light.giardino
    service: homeassistant.turn_on
  - data:
      entity_id: timer.garden_light
    service: timer.start
- id: '1558916049147'
  alias: Spegni luce giardino alla fine del timer
  trigger:
  - event_data:
      entity_id: timer.garden_light
    event_type: timer.finished
    platform: event
  action:
  - data:
      entity_id:
      - light.giardino
    service: homeassistant.turn_off
- id: '1533935635674'
  alias: Accendi luci esterno all'apertura del cancello
  trigger:
  - entity_id: binary_sensor.cancello_grande
    platform: state
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id:
      - light.vialetto
    service: homeassistant.turn_on
  - data:
      entity_id:
      - light.giardino
    service: homeassistant.turn_on
  - data:
      entity_id: timer.driveway_light
    service: timer.start
- id: '1533912649667'
  alias: Spegni luci esterne alla fine del timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.driveway_light
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
      - light.vialetto
  - data:
      entity_id:
      - light.giardino
    service: homeassistant.turn_off
- id: '1548270083547'
  alias: RFID Andrea
  trigger:
  - entity_id: sensor.pulsantiera_ingresso
    platform: state
    to: c5c30f
  condition: []
  action:
  - data:
      entity_id: switch.allarme_disattivato
    service: switch.toggle
  - alias: ''
    data:
      payload: '{ "code": "" }'
      retain: 'true'
      topic: /house/keypad/frontdoor/statusjson
    service: mqtt.publish
  - service_template: >
      {% if is_state("switch.allarme_disattivato", "off") %}
        script.close_covers
      {% else %}
      {% endif %}
- id: '1548273483548'
  alias: RFID Laura
  trigger:
  - entity_id: sensor.pulsantiera_ingresso
    platform: state
    to: b1c7d8
  condition: []
  action:
  - data:
      entity_id: switch.allarme_disattivato
    service: switch.toggle
  - alias: ''
    data:
      payload: '{ "code": "" }'
      retain: 'true'
      topic: /house/keypad/frontdoor/statusjson
    service: mqtt.publish
  - service_template: >
      {% if is_state("switch.allarme_disattivato", "off") %}
        script.close_covers
      {% else %}
      {% endif %}
- id: '1548620730929'
  alias: Gestione automazioni in caso di pioggia
  trigger:
  - entity_id: sensor.dark_sky_icon
    platform: state
    to: rain
  condition: []
  action:
  - data:
      entity_id: automation.bentornato_tapparelle
    service: automation.turn_off
- id: '1548620788206'
  alias: Gestione tapparelle quando non piove
  trigger:
  - entity_id: sensor.dark_sky_icon
    from: rain
    platform: state
  condition: []
  action:
  - data:
      entity_id: automation.bentornato_tapparelle
    service: automation.turn_on
- id: '1548620790215'
  alias: Gestione tapparelle quando non piove
  trigger:
  - entity_id: sensor.dark_sky_icon
    from: rain
    platform: state
  condition: []
  action:
  - data:
      entity_id: automation.bentornato_tapparelle
    service: automation.turn_on
- id: '1528689731929'
  alias: Chiusura tapparelle alla mattina
  trigger:
  - platform: time
    at: '05:00:00'
  condition: []
  action:
  - service: script.close_covers

