homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Device tracking
device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - andrea
      - laura

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: template
    sensors:
      pixel_battery:
        friendly_name: Andrea Samsung S9
        unit_of_measurement: "%"
        value_template: '{{ states.device_tracker.andrea_smartphone.attributes.battery|int }}'
        device_class: battery
  - platform: netgear_lte
    sensors:
      - sms
      - usage

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# MQTT
mqtt:
  password: !secret mqtt_password

light:
  - platform: mqtt
    name: "Andrea"
    command_topic: "/house/light/command"
    state_topic: "/house/light/status"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: yeelight
    devices:
      192.168.2.150:
        transition: 1000
        use_music_mode: False 
        save_on_change: False

google_assistant:
  project_id: home-4c8f5
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - group
    - scripts
  entity_config:
    script.tv_turn_on_off:
      name: "Accendi spegni TV"
      expose: true
    script.film_mode:
      name: "Modalità film"
      expose: true
    script.music_mode:
      name: "Modalità musica"
      expose: true  
    script.ligth_mode:
      name: "Modalità luce"
      expose: true
      
remote:
  - platform: xiaomi_miio
    name: andrea_remote
    host: 192.168.1.134
    token: !secret xiaomi_mioo_token
    slot: 1
    timeout: 5
    hidden: false
    commands:
      tv_vol_low:
        command:
          - raw:Z6VHADsCAAB7BgAAuggAAHoRAAA7IwAAeJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAQAAAAAAAAEAAQEBAQEBBQJAA
      tv_on_off:
        command:
          - raw:Z6VHACUCAABHAgAAeAYAALgIAABgEQAASSMAAHibAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEhAQEBAQEhIQEhISEhIQEBASEBAQEBISEhASEhISFhNQE=
telegram_bot:
  - platform: polling
    api_key: !secret telegram_tostombot_api_key
    allowed_chat_ids:
      - !secret telegram_andrea_chat_id
      - !secret telegram_laura_chat_id
      - !secret telegram_tostom_group_chat_id

notify:
  - name: telegram_tostom
    platform: telegram
    chat_id: !secret telegram_andrea_chat_id
  - platform: nfandroidtv
    name: tv_salotto
    host: 192.168.2.105
  - platform: netgear_lte
    name: sms_andrea
    target: !secret telephone_number_andrea
    
netgear_lte:
  - host: 192.168.5.1
    password: !secret netgear_lte_modem_password
   
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

switch:
  - platform: template
    switches:
      google_assistant_sync:
        value_template: "{{'off'}}"
        turn_on:
          service: google_assistant.request_sync
        turn_off:
          service: google_assistant.request_sync
          
climate:
  - platform: netatmo
    thermostat:
      - termostato_3
  
netatmo:
  api_key: !secret netatmo_api_key 
  secret_key: !secret netatmo_secret_key 
  username: !secret netatmo_username 
  password: !secret netatmo_password 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml




