homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
#   - type: legacy_api_password
   

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

recorder:
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - sensor.pulsantiera_ingresso

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

system_health:

# Enables a map showing the location of tracked devices
map:

# Device tracking
owntracks:
  max_gps_accuracy: 200
  waypoints: True
  waypoint_whitelist:
    - casa
    - lavoro_andrea

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: template
    sensors:
      pixel_battery:
        friendly_name: Andrea Samsung S9
        unit_of_measurement: "%"
        value_template: '{{ states.device_tracker.andrea_smartphone.attributes.battery|int }}'
        device_class: battery
  - platform: mqtt
    name: "Pulsantiera ingresso"
    state_topic: "/house/keypad/frontdoor/statusjson"
    value_template: "{{ value_json.code }}"
    json_attributes:
      - code
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
#  - platform: netgear_lte
#    sensors:
#      - sms
#      - usage

binary_sensor:
  - platform: mqtt
    name: "Cancello grande"
    state_topic: "/house/binary/gate/status"
    payload_on: "ON"
    payload_off: "OFF"
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    
media_player:
  - platform: androidtv
    name: TV del salotto
    host: 192.168.2.105
    adb_server_ip: 127.0.0.1
    apps:
      org.xbmc.kodi: "Kodi"
      com.netflix.ninja: "Netflix"
      com.spotify.tv.android: "Spotify"
      com.google.android.tvlauncher: "Homescreen"
      com.google.android.youtube.tv: "Youtube"

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1883
  username: homeassistant
  password: !secret mqtt_password
  
#tradfri:
#  host: 192.168.2.71

cover:
  - platform: mqtt
    name: ground_floor
    command_topic: "/house/cover/ground/set"
  - platform: mqtt
    name: first_floor
    command_topic: "/house/cover/first/set"
  - platform: group
    name: all
    entities:
      - cover.ground_floor
      - cover.first_floor


light:
  - platform: mqtt
    name: "Soggiorno"
    command_topic: "/house/light/living/command"
    state_topic: "/house/light/living/status"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Cucina"
    command_topic: "/house/light/kitchen/command"
    state_topic: "/house/light/kitchen/status"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Vialetto"
    command_topic: "/house/light/driveway/command"
    state_topic: "/house/light/driveway/status"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Giardino"
    command_topic: "/house/light/garden/command"
    state_topic: "/house/light/garden/status"
    payload_on: "ON"
    payload_off: "OFF"
    
yeelight:
  devices:
    192.168.2.133:
      name: Scrivania
      model: color1
      transition: 1000
      use_music_mode: False 
      save_on_change: False
    192.168.2.180:
      name: Studio
      model: ceiling3
      transition: 1000
      use_music_mode: False 
      save_on_change: False
    192.168.2.90:
      name: Comodino Andrea
      model: bslamp1
      transition: 1000
      use_music_mode: False 
      save_on_change: False
    192.168.2.63:
      name: Comodino Laura
      model: bslamp1
      transition: 1000
      use_music_mode: False 
      save_on_change: False
        
timer:
  driveway_light:
    duration: '00:10:00'
  garden_light:
    duration: '00:03:00'
  alarm_grace_time:
    duration: '00:10:00'
  alarm_back_home_time:
    duration: '00:01:00'

google_assistant:
  project_id: home-4c8f5
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - light
    - group
    - scripts
  entity_config:
    script.alarm_arm:
      name: "Attiva Allarme"
      expose: true
    script.alarm_disarm:
      name: "Disattiva Allarme"
      expose: true
    script.close_covers:
      name: "Chiudi tapparelle"
      expose: true
    script.open_covers:
      name: "Apri tapparelle"
      expose: true
    script.morning_covers:
      name: "Tapparelle al mattino"
      expose: true
    script.cinema_mode_on:
      name: "Avvia cinema"
      expose: true
    script.cinema_mode_of:
      name: "Stop cinema"
      expose: true
    cover.ground_floor:
      name: "Tapperelle Piano Terra"
      expose: true
    cover.first_floor:
      name: "Tapperelle Primo Piano"
      expose: true
    cover.all:
      expose: false
      
#fastdotcom:
      
    
telegram_bot:
  - platform: polling
    api_key: !secret telegram_tostombot_api_key
    allowed_chat_ids:
      - !secret telegram_andrea_chat_id
      - !secret telegram_laura_chat_id
      - !secret telegram_tostom_group_chat_id

notify:
  - name: telegram_tostom
    platform: telegram
    chat_id: !secret telegram_tostom_group_chat_id
  - platform: nfandroidtv
    name: tv_salotto
    host: 192.168.2.105
#  - platform: netgear_lte
#    name: sms_andrea
#    target: !secret telephone_number_andrea
#  - platform: netgear_lte
#    name: sms_laura
#    target: !secret telephone_number_laura

switch:
  - platform: mqtt
    name: "Sonoff Grande"
    state_topic: "stat/sonoffs20/POWER"
    command_topic: "cmnd/sonoffs20/POWER"
    availability_topic: "tele/sonoffs20/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Sonoff Piccolo"
    state_topic: "stat/sonoffs26/POWER"
    command_topic: "cmnd/sonoffs26/POWER"
    availability_topic: "tele/sonoffs26/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false  
  - platform: template
    switches:
      google_assistant_sync:
        value_template: "{{'off'}}"
        turn_on:
          service: google_assistant.request_sync
        turn_off:
          service: google_assistant.request_sync
  - platform: template
    switches:
      allarme_disattivato:
        value_template: "{{ is_state('alarm_control_panel.house', 'disarmed') }}"
        turn_on:
          service: script.alarm_disarm
        turn_off:
          service: script.alarm_arm 
          
climate:
  - platform: netatmo
  
netatmo:
  api_key: !secret netatmo_api_key 
  secret_key: !secret netatmo_secret_key 
  username: !secret netatmo_username 
  password: !secret netatmo_password 
  discovery: false
  
camera:
  - platform: mjpeg
    name: Livingroom Camera
    authentication: basic
    username: admin
    password: 83h9mvgA
    still_image_url: http://192.168.2.26/IMAGE.JPG
    mjpeg_url: http://192.168.2.26/mjpeg.cgi?user=admin&password=83h9mvgA&channel=0
    
shell_command:
  camera_center: 'curl -H "Authorization: Basic YWRtaW46ODNoOW12Z0E=" "http://192.168.2.26/pantiltcontrol.cgi?PanTiltPresetPositionMove=1"'
  camera_sx: 'curl -H "Authorization: Basic YWRtaW46ODNoOW12Z0E=" "http://192.168.2.26/pantiltcontrol.cgi?PanTiltPresetPositionMove=2"'
  camera_dx: 'curl -H "Authorization: Basic YWRtaW46ODNoOW12Z0E=" "http://192.168.2.26/pantiltcontrol.cgi?PanTiltPresetPositionMove=3"'
  camera_hide: 'curl -H "Authorization: Basic YWRtaW46ODNoOW12Z0E=" "http://192.168.2.26/pantiltcontrol.cgi?PanTiltPresetPositionMove=4"'
  
input_select:
  camera_control:
    name: Controllo Videocamera
    options:
      - "Sinistra"
      - "Centro"
      - "Destra"
      - "Nascondi"
    icon: mdi:camera-switch

konnected:
  access_token: NM6dxbbsRhP7AgkHqtVx6uxysQgTA0KIHd2UTNemCdsLjyCZ2etfVUJEJYnoMmBNGRMNfLZp29C9Iacrqb3In5ajA9scw3BCIH
  api_host: http://192.168.2.100:8123
  devices:
    - id: 68c63aab3b39
      binary_sensors:
        - zone: 1
          type: door
          name: 'Portoncino'
        - zone: 2
          type: window
          name: 'Bagno terra'
        - zone: 3
          type: door
          name: 'Garage Basculante'
        - zone: 4
          type: window
          name: 'Cucina'
        - zone: 5
          type: motion
          name: 'Garage'
        - zone: 6
          type: motion
          name: 'Ingresso'
    - id: b4e62d257a94
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Scale'
        - zone: 2
          type: window
          name: 'Salotto'
    - id: dc4f2218fddc
      binary_sensors:
        - zone: 1
          type: window
          name: 'Camera'
        - zone: 2
          type: window
          name: 'Bagno primo'
        - zone: 3
          type: window
          name: 'Cameretta'
        - zone: 4
          type: window
          name: 'Studio'
        - zone: 5
          type: window
          name: 'Soffitta'
          
remote:
  - platform: xiaomi_miio
    host: 192.168.2.170
    token: !secret xiaomi_miio_token

alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

ssdp:
zeroconf:




